# Minimum flip bits for int8 attacks, (paper)

In [50]:
import PyPDF2
import numpy as np
from scipy.spatial.distance import hamming

In [11]:
def extract_words_from_pdf(file_path):
    pdf_file = open(file_path, 'rb')
    reader = PyPDF2.PdfReader(pdf_file)

    word_array = []
    for page in reader.pages:
        text = page.extract_text()
        words = text.split()  # Split text into words
        word_array.extend(words)  # Add words to the array

    pdf_file.close()
    return word_array

In [24]:
def table_code_words(input_array):

    table_code_words = np.zeros((255,), dtype=np.ndarray)

    for i in range(255):
        table_code_words[i] = input_array[3 + i*4]

    return table_code_words

In [32]:
def table_binary_code_words(input_array):

    table_code_words_binary = np.zeros((255,), dtype=np.ndarray)

    for i in range(255):
        if i < 127:
            table_code_words_binary[i + 128] = [int(bit) for bit in input_array[3 + i*4]]
        else:
            table_code_words_binary[i - 127] = [int(bit) for bit in input_array[3 + i*4]]

    return table_code_words_binary

In [26]:
pdf_file_path = "D:\DP\DP\Code\HammingCode(12,8,3)_C12-3.pdf"
C_12_3 = extract_words_from_pdf(pdf_file_path)

In [38]:
# Print the extracted text
for text in C_12_3:
    print(text)


1
00000001
4095
111111111111
2
00000010
2030
011111101110
3
00000011
2065
100000010001
4
00000100
1663
011001111111
5
00000101
2432
100110000000
6
00000110
401
000110010001
7
00000111
3694
111001101110
8
00001000
1471
010110111111
9
00001001
2624
101001000000
10
00001010
593
001001010001
11
00001011
3502
110110101110
12
00001100
960
001111000000
13
00001101
3135
110000111111
14
00001110
1070
010000101110
15
00001111
3025
101111010001
16
00010000
991
001111011111
17
00010001
3104
110000100000
18
00010010
1073
010000110001
19
00010011
3022
101111001110
20
00010100
1440
010110100000
21
00010101
2655
101001011111
22
00010110
590
001001001110
23
00010111
3505
110110110001
24
00011000
1632
011001100000
25
00011001
2463
100110011111
26
00011010
398
000110001110
27
00011011
3697
111001110001
28
00011100
31
000000011111
29
00011101
4064
111111100000
30
00011110
2033
011111110001
31
00011111
2062
100000001110
32
00100000
4039
111111000111
33
00100001
56
000000111000
34
00100010
2089
100000101001

In [48]:
table_code_words_binary = table_binary_code_words(C_12_3)
print(table_code_words_binary)



[list([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0])
 list([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1])
 list([1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0])
 list([0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1])
 list([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1])
 list([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0])
 list([1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1])
 list([0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0])
 list([1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1])
 list([0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0])
 list([1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1])
 list([0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0])
 list([1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0])
 list([0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1])
 list([1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0])
 list([0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1])
 list([1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1])
 list([0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0])
 list([1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1])
 list([0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0])
 list([1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0])
 list([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1])
 list([1, 1, 0, 1, 0, 0, 1, 1, 0

In [49]:
table_hamming_distance = np.full((255,255), 255, dtype=np.uint8)
np.fill_diagonal(table_hamming_distance, 0)
print(table_hamming_distance)

[[  0 255 255 ... 255 255 255]
 [255   0 255 ... 255 255 255]
 [255 255   0 ... 255 255 255]
 ...
 [255 255 255 ...   0 255 255]
 [255 255 255 ... 255   0 255]
 [255 255 255 ... 255 255   0]]


In [51]:
for i in range(255):
    for j in range(255):
        if i != j:
            code_word_bin = table_code_words_binary[i]
            code_word_bin_2 = table_code_words_binary[j]
            table_hamming_distance[i][j] = hamming(code_word_bin, code_word_bin_2) * len(code_word_bin)



[[ 0 12  9 ...  4  5  7]
 [12  0  3 ...  8  7  5]
 [ 9  3  0 ...  7  8  4]
 ...
 [ 4  8  7 ...  0  3  9]
 [ 5  7  8 ...  3  0 12]
 [ 7  5  4 ...  9 12  0]]


In [54]:
print(table_hamming_distance)

[[ 0 12  9 ...  4  5  7]
 [12  0  3 ...  8  7  5]
 [ 9  3  0 ...  7  8  4]
 ...
 [ 4  8  7 ...  0  3  9]
 [ 5  7  8 ...  3  0 12]
 [ 7  5  4 ...  9 12  0]]
